project:
  type: website
  output-dir: docs

website:
  title: "JIBLM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes.qmd
        text: "Course Notes"
        
format:
  html:
    theme:
      - cosmo
    css: styles.scss
    toc: true
    backgroundcolor: "#FBF5DE"
    page-layout: full

editor: visual

