---
title: "Information for Authors of Course Notes"
---

Course Notes are freely downloadable, professionally refereed, classroom-tested notes which constitute a full course or sequence of full courses. Course Notes are intended

1.  for instructors to use as notes for their course
2.  for instructors to modify to suit the needs of their students
3.  for students to use to study a topic independently.

Instructors are encouraged to contact authors for guidance in the use of Course Notes.

# Publication Requirements

### Abstract

Course Notes should include an abstract with sufficient detail to assist users who are viewing multiple sets of Course Notes in determining which set best meets their needs.

### Classroom Testing

Course Notes should be thoroughly class tested and provide a successful course in their present formulation. Course Notes that have not been thoroughly vetted through multiple cycles of classroom testing rarely pass the refereeing process.

### Content

Course Notes should be mathematically correct and well written, consisting primarily of a sequence of problems to solve or theorems to prove. Course Notes should provide material for a full course or sequence of courses. The student version, excluding supplementary materials and appendices, should span at most seventy pages per semester of material for the course.

### Copyrights

Authors submitting materials retain copyright and cede to JIBLM the right to display published materials in perpetuity. Anyone reproducing or displaying JIBLM publications should clearly display the journal name, title, issue and number. Reproduced materials may be distributed provided that no charge is levied to the users beyond the cost of reproduction.

### Introduction

Course Notes should maximize the opportunity for a successful implementation by providing potential instructors with a clear understanding of your implementation of the course. The introduction should therefore include

-   a description of the course you taught,
-   the approximate class size,
-   the number of times the course has been taught,
-   its level and role within the broader curriculum,
-   your expectations and grading of the students,
-   the exact portion of the notes covered in your course,
-   any unusual characteristics of the course or classroom such as technology, multiple white boards, special seating, etc., and
-   any other information that will be useful to a less experienced instructor.

### Pedagogy

Course Notes should adhere to an IBL pedagogy that utilizes presentations or student-centered activities to develop in students the confidence and ability to do mathematics on their own. Instructors typically supply students with carefully crafted activities or course notes consisting of a sequence of definitions, problems or theorems. Instructors then serve as mentors, listening to the students, reviewing their work, and giving them the minimal information they need to understand the defined concepts, solve the problems, or prove the theorems.

### Source Availability

As copyrights are retained by the author, we do not provide the source for download. However, based on our anecdotal experience, authors contacted have been very willing to share their expertise, experience and source with instructors wishing to use the author's notes. Because authors often revise and improve notes, contacting the author directly may well result in a more current, improved version.

### Submissions

Course Notes should be sent via email to the Course Notes Editor David Clark along with a completed Submissions Form using the LaTeX templates provided. The form **template.tex** serves as:

-   a guide to typesetting your course notes, and
-   a template to be modified to produce your print ready submission.

### To get started

-   download the Submission Form: <a href="./author_files/submission_cn.tex" download="submission_cn.tex"> submission_cn.tex </a>

-   download the LaTeX template: <a href="./author_files/template_cn.tex" download="template_cn.tex">template_cn.tex </a>,

-   download the JIBLM Formatting Package: <a href="./author_files/jiblm_cn.tex" download="jiblm_cn.tex">jiblm_cn.tex</a>,

-   place **jiblm_cn.tex** and **template_cn.tex** in the same directory,

-   compile **template_cn.tex** and read the output, and

-   place your notes into a copy of the file **template.tex**.

Do not modify **jiblm_cn.tex**. If you encounter any difficulties, please contact the Technical Editor Ted Mahavier for assistance.

# Additional Information

### Joint Authorship

Some Course Notes come with a pedigree, having been modified from another instructor's notes. JIBLM encourages such adaptations. To handle these instances, JIBLM adheres to the following two conventions regarding authorship.

For cases where an author modifies another's notes:

If each of X and Y is an author, then the relation X \< Y indicates that the Course Notes were originally authored by Y and subsequently modified by X, who takes full responsibility for the current version. While Y is credited with the genesis of the notes, s/he makes no claim to the accuracy of the current version which may or may not reflect her/his original vision.

For cases where an author reproduces another's notes, for example, posthumously:

If each of X and Y is an author, then the relation X \<\< Y indicates that these notes were originally authored by Y and subsequently prepared for submission to JIBLM by X without significant modification and with appropriate permissions. While Y is credited with the genesis of the notes, X takes full responsibility for the current version.

### Student and Instructor Versions

As an author, you may wish to create both a student and an instructor version of your course notes. The instructor version will consist of the student version along with additional advice, comments and guidance to the instructor that might unnecessarily clutter the student version. Upon publication, both versions will be available on-line from the journal. The downloadable template described below allows you to create one LaTeX document that will produce both versions by toggling one commented line in the beginning of the document.

### Submission and Page Costs

There are no submission or page costs associated with publishing in JIBLM.

### Updating Course Notes

In order to keep the highest quality notes available online, JIBLM encourages the revision of published notes. Should an author desire corrections or modifications, the author may submit a complete list of revisions along with a new submission to replace the original submission. The revised version will be refereed, and will replace the old version if it is accepted. Such submissions will be replaced in December and June to assure that faculty using course notes on-line will not be effected.
