---
title: "Other Materials"
---

## Modules

Modules are freely-downloadable, professionally-refereed, classroom-tested notes providing material for an inquiry-based unit on a specific topic. A Module will cover less than a full course. It might be as small as a single idea covered in one day, or as large as an independent topic spanning several weeks. A Module might be some portion of another course of study, but it must stand alone as a logically complete unit.

Modules are intended:

-   for instructors to use as part of a course,
-   for instructors to modify for use as part of their course, or
-   for students to study a topic independently.

Instructors are encouraged to contact authors for guidance in the use of Modules.

### [List of Available Modules](modules/modules.qmd)

## Unrefereed Course Notes

These two collections of notes are offered free of charge and may be reproduced and distributed provided that no charge is levied to the users beyond the cost of reproduction.


### [Individual Contributions](unrefereed_notes/unrefereed_notes.qmd)

These notes were obtained by one of the original editors prior to the inception of JIBLM. Many have been used for years, if not decades, and are (in our opinion) excellent notes. JIBLM encourages instructors using these notes to modify them as needed to suit their own courses and then submit them to JIBLM for consideration as refereed publications. Special designations for authoring notes created by one individual and adapted to a course by a second are described in the Joint Authorship section of the Information for Authors of Course Notes.

<!-- [List of Available Materials](unrefereed_notes/unrefereed_notes.qmd) -->

### [Guilford College Collection](guilfordjournal/guilford.qmd)

These notes come from "Monographs in Undergraduate Mathematics," founded by J. R. Boyd and developed by the faculty of the Department of Mathematics at Guilford College over the period from 1969 to 1994. When this series became inactive, these notes were donated under the condition that they remain unaltered and protected by Guilford copyright.

